### ISSUE TITLE
Uninformative error message while trying to extract PMID

### ISSUE THREAD

**Issue by zl2465** [kamclean/impactr#3]
Thank you for your work on this interesting and awesome package!

I have tried to use this package to extract altmetric information of articles published by my coworkers. But I noticed that many of them failed and gave me the following error message:

"Error in seq.default(max(out$year) + 1, max(df$year)) : 'from' must be a finite number"

Here are my sample codes:
```
out_pubmed <- impactr::extract_pmid(pmid = c(26569447))

out_doi <- impactr::extract_doi(doi = '10.1016/j.contraception.2015.11.002')
```
Interestingly, the extract doi method does return some results but all the altmetrice information are missing even though the Altmetrice website shows that it has been collecting data on influence and citations (https://www.altmetric.com/details/6712903). 
 
Thanks!

**Comment by kamclean** [comment]
Sorry for the delay in replying - have only just got round to doing a big update with impactr!

I'm not 100% sure what was causing the error here - on the latest update this seems to be fixed on your reprex :).

Strange about the altmetric here - it is displayed oddly on the website (https://www.altmetric.com/details/6712903) - I haven't seen that before but I presume this means the altmetric is not extractable (I note that it's tracked by PLum metrics here: https://plu.mx/plum/a/?doi=10.1016/j.contraception.2015.11.002). Unfortunately, there's no free access to Plum metrics, so it's not something that ImpactR can support.

Thanks for highlighting and really glad to hear you like 😄 - will aim to be faster at addressing any further issues!
